# Generated by Django 4.0.4 on 2022-06-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=30)),
                ('contact_number', models.IntegerField()),
                ('next_purchase', models.DateField()),
            ],
        ),
    ]
