# Generated by Django 4.0.4 on 2022-06-04 22:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='next_purchase',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
