# Generated by Django 4.0.4 on 2022-06-08 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_provider_next_purchase'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
