# Generated by Django 4.0.5 on 2022-06-19 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_alter_provider_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'Provider', 'verbose_name_plural': 'Providers'},
        ),
    ]
