# Generated by Django 4.0.4 on 2022-06-07 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('fantacy_name', models.CharField(max_length=40)),
                ('namer_phone', models.FloatField()),
                ('date_create', models.DateTimeField()),
                ('adess', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('Cuit', models.CharField(max_length=30, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
