# Generated by Django 4.0.4 on 2022-06-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appclientes', '0004_alter_clients_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
