# Generated by Django 4.0.4 on 2022-06-06 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('price', models.FloatField()),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('SKU', models.CharField(max_length=15, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
